# Write your MySQL query statement below
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary
FROM 
(SELECT * , 
DENSE_RANK() OVER (
    PARTITION BY DEPARTMENTID
    ORDER BY SALARY DESC 
) AS RNK
FROM EMPLOYEE
)E
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE E.RNK<=3
ORDER BY D.NAME,E.SALARY DESC;
