# Write your MySQL query statement below
SELECT  D.NAME AS Department, E.NAME AS Employee,E.SALARY AS Salary
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D ON E.DEPARTMENTID=D.ID
WHERE E.SALARY=(
    SELECT MAX(SALARY)
    FROM EMPLOYEE
    WHERE DEPARTMENTID=D.ID 
);